/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetHello200 } from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApp = () => {
  /**
   * @summary Returns a hello message
   */
  const appControllerGetHello = (
    options?: SecondParameter<typeof api<AppControllerGetHello200>>,
  ) => {
    return api<AppControllerGetHello200>(
      { url: `http://localhost:8000/api`, method: "GET" },
      options,
    );
  };
  return { appControllerGetHello };
};
export type AppControllerGetHelloResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApp>["appControllerGetHello"]>>
>;
