import "dotenv/config";
import fs from "fs";
import path from "path";
import { getPayload } from "payload";
import { fileURLToPath } from "url";
import config from "../payload.config.ts";
import { Page, Post } from "@/payload-types.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const BACKUP_DIR = path.resolve(__dirname, "../../backup");
const MEDIA_DIR = path.join(BACKUP_DIR, "media");

// ---------------------------------------------------------------------------
// Types (minimal, only what we need)
// ---------------------------------------------------------------------------

interface BackupMediaDoc {
  id: string | number;
  alt?: string;
  filename?: string;
  mimeType?: string;
}

interface BackupUserDoc {
  id: string | number;
  email: string;
  name?: string;
}

interface BackupPostDoc {
  id: string | number;
  title: string;
  slug: string;
  content: unknown;
  featuredImage?: string | number | BackupMediaDoc | null;
  author?: string | number | BackupUserDoc | null;
  publishedDate?: string;
}

interface BackupPageDoc {
  id: string | number;
  title: string;
  slug: string;
  layout?: unknown[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJson<T>(filePath: string): T {
  const raw = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(raw) as T;
}

/**
 * Recursively walk a value and replace any occurrence of old IDs (from the
 * id map) with the newly created IDs.  Handles strings, numbers, arrays and
 * plain objects.  Does NOT modify non-id primitive values.
 */
function remapIds(value: unknown, idMap: Map<string | number, string | number>): unknown {
  if (value === null || value === undefined) return value;

  if (typeof value === "string" || typeof value === "number") {
    return idMap.get(value) ?? value;
  }

  if (Array.isArray(value)) {
    return value.map((item) => remapIds(item, idMap));
  }

  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      result[k] = remapIds(v, idMap);
    }
    return result;
  }

  return value;
}

/**
 * Extract the raw ID from either a primitive or a populated relationship object.
 */
function extractId(
  ref: string | number | { id: string | number } | null | undefined,
): string | number | null {
  if (ref === null || ref === undefined) return null;
  if (typeof ref === "string" || typeof ref === "number") return ref;
  return ref.id ?? null;
}

/**
 * Strip Payload-managed metadata fields that must not be sent on create.
 */
function stripMeta(doc: Record<string, unknown>): Record<string, unknown> {
  const STRIP = new Set([
    "id",
    "createdAt",
    "updatedAt",
    "sizes", // regenerated by Payload on upload
    "_status",
    "globalType",
  ]);
  return Object.fromEntries(Object.entries(doc).filter(([k]) => !STRIP.has(k)));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function seed() {
  console.log("=".repeat(60));
  console.log("  Payload CMS — Seed from Backup");
  console.log("=".repeat(60));

  // Check backup exists
  if (!fs.existsSync(BACKUP_DIR)) {
    throw new Error(`Backup directory not found at ${BACKUP_DIR}. Run \`pnpm backup\` first.`);
  }

  const payload = await getPayload({ config });

  /**
   * Global map from old (backup) IDs → new (fresh DB) IDs.
   * Used to rewrite relationship references across all collections.
   */
  const idMap = new Map<string | number, string | number>();

  // ── 1. Users ──────────────────────────────────────────────────────────────
  console.log("\n[1/5] Users");
  const backupUsers = fs.existsSync(path.join(BACKUP_DIR, "users.json"))
    ? readJson<BackupUserDoc[]>(path.join(BACKUP_DIR, "users.json"))
    : [];

  for (const user of backupUsers) {
    try {
      const created = await payload.create({
        collection: "users",
        data: {
          email: user.email,
          // A default password — the admin should change this after seeding
          password: "ChangeMe123!",
        },
        overrideAccess: true,
      });
      idMap.set(user.id, created.id);
      console.log(`  ✔ User: ${user.email} (${user.id} → ${created.id})`);
    } catch (err: unknown) {
      console.warn(`  ⚠ Could not create user ${user.email}: ${(err as Error).message}`);
    }
  }

  // ── 2. Media ──────────────────────────────────────────────────────────────
  console.log("\n[2/5] Media");
  const backupMedia = fs.existsSync(path.join(BACKUP_DIR, "media.json"))
    ? readJson<BackupMediaDoc[]>(path.join(BACKUP_DIR, "media.json"))
    : [];

  for (const doc of backupMedia) {
    if (!doc.filename) {
      console.warn(`  ⚠ Skipping media ${doc.id} — no filename`);
      continue;
    }

    const filePath = path.join(MEDIA_DIR, doc.filename);

    if (!fs.existsSync(filePath)) {
      console.warn(`  ⚠ Skipping ${doc.filename} — file not found in backup/media`);
      continue;
    }

    try {
      const created = await payload.create({
        collection: "media",
        data: { alt: doc.alt || doc.filename },
        filePath,
        overrideAccess: true,
      });
      idMap.set(doc.id, created.id);
      console.log(`  ✔ Media: ${doc.filename} (${doc.id} → ${created.id})`);
    } catch (err: unknown) {
      console.warn(`  ⚠ Could not upload ${doc.filename}: ${(err as Error).message}`);
    }
  }

  // ── 3. Pages ──────────────────────────────────────────────────────────────
  console.log("\n[3/5] Pages");
  const backupPages = fs.existsSync(path.join(BACKUP_DIR, "pages.json"))
    ? readJson<BackupPageDoc[]>(path.join(BACKUP_DIR, "pages.json"))
    : [];

  for (const doc of backupPages) {
    try {
      const raw = stripMeta(doc as unknown as Record<string, unknown>);
      const remapped = remapIds(raw, idMap) as Record<string, unknown>;

      const created = await payload.create({
        collection: "pages",
        data: remapped as unknown as Page,
        overrideAccess: true,
      });
      idMap.set(doc.id, created.id);
      console.log(`  ✔ Page: "${doc.title}" [/${doc.slug}] (${doc.id} → ${created.id})`);
    } catch (err: unknown) {
      console.warn(`  ⚠ Could not create page "${doc.title}": ${(err as Error).message}`);
    }
  }

  // ── 4. Posts ──────────────────────────────────────────────────────────────
  console.log("\n[4/5] Posts");
  const backupPosts = fs.existsSync(path.join(BACKUP_DIR, "posts.json"))
    ? readJson<BackupPostDoc[]>(path.join(BACKUP_DIR, "posts.json"))
    : [];

  for (const doc of backupPosts) {
    try {
      const raw = stripMeta(doc as unknown as Record<string, unknown>);

      // Resolve relationship references before remapping
      const authorId = extractId(doc.author as BackupUserDoc | string | number | null);
      const featuredImageId = extractId(
        doc.featuredImage as BackupMediaDoc | string | number | null,
      );

      const remapped = remapIds(raw, idMap) as Record<string, unknown>;

      // Override with the resolved (remapped) IDs
      if (authorId !== null) {
        remapped.author = idMap.get(authorId) ?? authorId;
      }
      if (featuredImageId !== null) {
        remapped.featuredImage = idMap.get(featuredImageId) ?? featuredImageId;
      }

      const created = await payload.create({
        collection: "posts",
        data: remapped as unknown as Post,
        overrideAccess: true,
      });
      idMap.set(doc.id, created.id);
      console.log(`  ✔ Post: "${doc.title}" [/${doc.slug}] (${doc.id} → ${created.id})`);
    } catch (err: unknown) {
      console.warn(`  ⚠ Could not create post "${doc.title}": ${(err as Error).message}`);
    }
  }

  // ── 5. Globals ────────────────────────────────────────────────────────────
  console.log("\n[5/5] Globals");

  const globalsPath = path.join(BACKUP_DIR, "globals.json");
  if (!fs.existsSync(globalsPath)) {
    console.warn("  ⚠ globals.json not found — skipping globals.");
  } else {
    const allGlobals = readJson<Record<string, Record<string, unknown>>>(globalsPath);

    const globalSlugs = ["header", "footer", "site-settings"] as const;

    for (const slug of globalSlugs) {
      const data = allGlobals[slug];
      if (!data) {
        console.warn(`  ⚠ No data found for global "${slug}" — skipping.`);
        continue;
      }

      try {
        const raw = stripMeta(data);
        const remapped = remapIds(raw, idMap) as Record<string, unknown>;

        await payload.updateGlobal({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          slug: slug as any,
          data: remapped as Parameters<typeof payload.updateGlobal>[0]["data"],
          overrideAccess: true,
        });
        console.log(`  ✔ Global: ${slug}`);
      } catch (err: unknown) {
        console.warn(`  ⚠ Could not update global "${slug}": ${(err as Error).message}`);
      }
    }
  }

  // ── Done ──────────────────────────────────────────────────────────────────
  console.log("\n" + "=".repeat(60));
  console.log(`  Seed complete. ${idMap.size} document(s) mapped.`);
  console.log("  ⚠  All seeded users have the password: ChangeMe123!");
  console.log("=".repeat(60));

  process.exit(0);
}

seed().catch((err) => {
  console.error("\nSeed failed:", err);
  process.exit(1);
});
